$InstanceName    = "MyInstance"
$Distro          = "ubuntu\24.04"
$LinuxUsername   = "myuser"
$LinuxGecos      = "My User"
$GitName         = "Tom Borglum"
$GitEmail        = "tom.borglum@gmail.com"
$WindowsUsername = "tombo"
