$DistroTemplatePath   = "ubuntu\24.04"
$DistroInstallName    = "Ubuntu-24.04"
$GitName              = "Tom Borglum"
$GitEmail             = "tom.borglum@gmail.com"
$InstanceName         = "MyInstance"
$LinuxGecos           = "My User"
